### PR TITLE
Feature - Add Discord webhook logging

### PR DESCRIPTION
**Pull request by Firav**
Not sure if this is something that interests you, but I've added discord logging for captured phrases.

### CODE REVIEW

**Comment by YouHaveTrouble** [comment]
Sounds good. It would probably better to separate the webhook from the option to just log the detections

**Comment by Firav** [comment]
> Sounds good. It would probably better to separate the webhook from the option to just log the detections

Thats definitely something I can do. Just didnt know if you wanted to further complicate the logic within that function.

**Comment by Firav** [comment]
> Sounds good. It would probably better to separate the webhook from the option to just log the detections

Fixed

**Comment by YouHaveTrouble** [comment]
I checked the dependency you used for the webhook. It seems like there might be issues when it comes to licensing, since the gist they're based on is ARR. This project is under GPL-3 license and I would prefer not to use anything that could not adhere to that.

**Comment by Firav** [comment]
Would a dependency that's licensed under MIT work?

**Comment by YouHaveTrouble** [comment]
Yes, as long as it's not proprietary license model it should be fine

**Comment by Firav** [comment]
I'm looking at this library, do you approve?
https://github.com/eduardomcb/discord-webhook

**Comment by YouHaveTrouble** [comment]
looks good, if it works, then you can go with that!

**Comment by Firav** [comment]
> I'm looking at this library, do you approve? https://github.com/eduardomcb/discord-webhook

This library turned into a headache to try and depend, so I'm just going to keep this build private and not bother with this PR.

**Pull request closed without merging**
